name: Playwright Tests
on:
    push:
        branches: [main, smoke-test]
    pull_request:
        branches: [main, smoke-test]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'yarn'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install Playwright Browsers
              run: yarn playwright install --with-deps

            - name: Run Playwright tests
              run: yarn playwright test projects/documentation/e2e/published.spec.ts

            - name: Upload Playwright Report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
